# justfile — generated by justx · the justfile companion
# https://github.com/amberpixels/just-x
#
# Blocks between `# >>> justx:<id>` and `# <<< justx:<id>` are managed by justx.
# Edit anything outside the fences freely; `j @upgrade` (v2) re-syncs managed blocks.

# >>> justx:fmt (managed) — `j @upgrade` re-syncs; remove these fences to take over
# format Go code - rewrites to canonical form
fmt:
    go tool standardgo fmt ./...
# <<< justx:fmt

# >>> justx:lint (managed) — `j @upgrade` re-syncs; remove these fences to take over
# lint Go code - reports findings, changes nothing
lint:
    go tool standardgo ./...
# <<< justx:lint

# >>> justx:fix (managed) — `j @upgrade` re-syncs; remove these fences to take over
# auto-fix what can be fixed - run on a clean tree and read the diff
fix:
    go tool standardgo ./... --fix
# <<< justx:fix

# >>> justx:test (managed) — `j @upgrade` re-syncs; remove these fences to take over
# run tests
test:
    go test ./...
# <<< justx:test

# >>> justx:build (managed) — `j @upgrade` re-syncs; remove these fences to take over
# build
build:
    go build ./...
# <<< justx:build

# >>> justx:ci (managed) — `j @upgrade` re-syncs; remove these fences to take over
# run all checks - read-only, safe for CI
ci: lint test
# <<< justx:ci
