# justfile — generated by justx · the justfile companion
# https://github.com/amberpixels/just-x
#
# Blocks between `# >>> justx:<id>` and `# <<< justx:<id>` are managed by justx.
# Edit anything outside the fences freely; `j @upgrade` (v2) re-syncs managed blocks.

# standardgo carries the ruleset and the golangci-lint engine in one binary, so this
# repo holds no lint config of its own. It is run via `go run`, not a go.mod tool
# directive, to keep it out of this library's dependency graph.
# The fmt/lint/fix/test fences are removed for the same reason - they must not resync.
standardgo := "github.com/amberpixels/standardgo/cmd/standardgo@v0.1.1"

# Every module in this repo. Each has its own go.mod, so each needs its own run.
modules := ". x/mock x/belint"

# The floor this library promises to support. Keep in sync with the `go` directive
# in go.mod - that is the number consumers actually see. CI passes FLOOR_GO=local,
# having already installed the floor toolchain, so it never downloads a second one.
floor_go := env("FLOOR_GO", "go1.25.0")

# Default recipe: format. Rewrites files, but decides nothing - every change it
# makes is mechanical. `just fix` is the one that applies judgement.
default: fmt

# format Go code - rewrites to canonical form
fmt:
    for m in {{ modules }}; do (cd "$m" && go run {{ standardgo }} fmt ./...) || exit 1; done

# lint Go code - reports findings, changes nothing
lint:
    for m in {{ modules }}; do echo "== lint $m =="; (cd "$m" && go run {{ standardgo }} ./...) || exit 1; done

# auto-fix what can be fixed - run on a clean tree and read the diff
fix:
    for m in {{ modules }}; do (cd "$m" && go run {{ standardgo }} ./... --fix) || exit 1; done

# run tests
test:
    for m in {{ modules }}; do echo "== test $m =="; (cd "$m" && go test ./...) || exit 1; done

# check that the go.mod floor still builds and vets, standalone
floor:
    for m in {{ modules }}; do echo "== floor $m =="; (cd "$m" && GOWORK=off GOTOOLCHAIN={{ floor_go }} go build ./... && GOWORK=off GOTOOLCHAIN={{ floor_go }} go vet ./...) || exit 1; done

# >>> justx:build (managed) — `j @upgrade` re-syncs; remove these fences to take over
# build
build:
    go build ./...
# <<< justx:build

# run all checks - read-only, safe for CI
ci: lint test floor
